name: "test"
on:
  push:
    branches:
      - "!dependabot/*"
      - "*"
  pull_request:
    branches:
      - "*"
env:
  GO_VERSION: "~1.20.4"
jobs:
  lint:
    name: "Lint"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-go@v4"
        with:
          go-version: "${{ env.GO_VERSION }}"
          cache: "true"
      - uses: "authzed/actions/go-mod-tidy@main"
      - uses: "authzed/actions/gofumpt@main"
      - uses: "authzed/actions/golangci-lint@main"
  test:
    name: "Test"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-go@v4"
        with:
          go-version: "${{ env.GO_VERSION }}"
          cache: "true"
      - uses: "authzed/actions/go-test@main"
